export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    location TEXT NOT NULL,
    scene TEXT NOT NULL,
    owner TEXT NOT NULL,
    participants_json TEXT NOT NULL,
    industry TEXT NOT NULL,
    tickers_json TEXT NOT NULL,
    tags_json TEXT NOT NULL,
    summary TEXT NOT NULL,
    theses_json TEXT NOT NULL,
    confidence INTEGER NOT NULL DEFAULT 50,
    source_reliability INTEGER NOT NULL DEFAULT 50,
    status TEXT NOT NULL DEFAULT '草稿',
    sensitivity TEXT NOT NULL DEFAULT '内部',
    transcript TEXT NOT NULL DEFAULT '',
    evidence_json TEXT NOT NULL,
    next_action TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_date ON conversations(date DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_status_due ON conversations(status, due_date)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_industry ON conversations(industry)`,
  `CREATE TABLE IF NOT EXISTS uploads (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    object_key TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_uploads_conversation_id ON uploads(conversation_id)`,
  `CREATE TABLE IF NOT EXISTS search_chunks (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    ordinal INTEGER NOT NULL DEFAULT 0,
    content TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    UNIQUE(conversation_id, kind, ordinal)
  )`,
  `CREATE TABLE IF NOT EXISTS transcription_jobs (
    id TEXT PRIMARY KEY,
    upload_id TEXT NOT NULL UNIQUE,
    conversation_id TEXT NOT NULL,
    provider TEXT NOT NULL DEFAULT 'openai',
    model TEXT NOT NULL DEFAULT 'gpt-4o-transcribe-diarize',
    status TEXT NOT NULL DEFAULT 'queued',
    raw_transcript TEXT NOT NULL DEFAULT '',
    corrected_transcript TEXT NOT NULL DEFAULT '',
    segments_json TEXT NOT NULL DEFAULT '[]',
    structure_json TEXT NOT NULL DEFAULT '{}',
    error_message TEXT NOT NULL DEFAULT '',
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (upload_id) REFERENCES uploads(id),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_transcription_jobs_conversation ON transcription_jobs(conversation_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS audit_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    actor_id TEXT,
    actor_email TEXT,
    detail_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_events(entity_type, entity_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS wiki_pages (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    page_type TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    content_md TEXT NOT NULL,
    backlinks_json TEXT NOT NULL DEFAULT '[]',
    source_ids_json TEXT NOT NULL DEFAULT '[]',
    health_score INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    generated_by TEXT NOT NULL DEFAULT 'compiler',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_wiki_pages_type_updated ON wiki_pages(page_type, updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS conversation_access (
    conversation_id TEXT PRIMARY KEY,
    department TEXT NOT NULL DEFAULT '投研部',
    industry_group TEXT NOT NULL DEFAULT '*',
    project_group TEXT NOT NULL DEFAULT '二级市场',
    sensitivity TEXT NOT NULL DEFAULT '内部',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_conversation_access_scope ON conversation_access(department, industry_group, project_group, sensitivity)`,
  `CREATE TABLE IF NOT EXISTS user_access_profiles (
    user_id TEXT PRIMARY KEY,
    email TEXT NOT NULL DEFAULT '',
    departments_json TEXT NOT NULL DEFAULT '[]',
    industries_json TEXT NOT NULL DEFAULT '[]',
    projects_json TEXT NOT NULL DEFAULT '[]',
    max_sensitivity TEXT NOT NULL DEFAULT '内部',
    can_export INTEGER NOT NULL DEFAULT 0,
    can_download_audio INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS knowledge_governance (
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    owner TEXT NOT NULL DEFAULT '',
    verification_status TEXT NOT NULL DEFAULT '草稿',
    valid_until TEXT NOT NULL DEFAULT '',
    next_review_at TEXT NOT NULL DEFAULT '',
    version INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (entity_type, entity_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_governance_review ON knowledge_governance(next_review_at, verification_status)`,
  `CREATE TABLE IF NOT EXISTS content_versions (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    snapshot_json TEXT NOT NULL,
    change_summary TEXT NOT NULL DEFAULT '',
    actor_id TEXT,
    actor_email TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_versions_entity ON content_versions(entity_type, entity_id, version DESC)`,
  `CREATE TABLE IF NOT EXISTS research_feedback (
    id TEXT PRIMARY KEY,
    question TEXT NOT NULL,
    answer_json TEXT NOT NULL,
    source_ids_json TEXT NOT NULL DEFAULT '[]',
    feedback_type TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    model_version TEXT NOT NULL DEFAULT 'evidence-synthesis-v1',
    actor_id TEXT,
    actor_email TEXT,
    status TEXT NOT NULL DEFAULT '待处理',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_feedback_status_created ON research_feedback(status, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS knowledge_gaps (
    id TEXT PRIMARY KEY,
    question TEXT NOT NULL,
    suggestions_json TEXT NOT NULL DEFAULT '[]',
    actor_id TEXT,
    actor_email TEXT,
    status TEXT NOT NULL DEFAULT '待调研',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS follows (
    id TEXT PRIMARY KEY,
    actor_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_value TEXT NOT NULL,
    cadence TEXT NOT NULL DEFAULT 'daily',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(actor_id, entity_type, entity_value)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_follows_actor ON follows(actor_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    actor_id TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    read_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_actor_read ON notifications(actor_id, read_at, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS search_audit (
    id TEXT PRIMARY KEY,
    actor_id TEXT,
    query TEXT NOT NULL,
    filters_json TEXT NOT NULL DEFAULT '{}',
    knowledge_domains_json TEXT NOT NULL DEFAULT '[]',
    result_count INTEGER NOT NULL DEFAULT 0,
    elapsed_ms INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_search_audit_actor_created ON search_audit(actor_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS source_documents (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL UNIQUE,
    filename TEXT NOT NULL,
    media_type TEXT NOT NULL DEFAULT 'text/html',
    publisher TEXT NOT NULL DEFAULT '',
    published_at TEXT NOT NULL,
    event_at TEXT NOT NULL DEFAULT '',
    source_url TEXT NOT NULL DEFAULT '',
    object_key TEXT NOT NULL DEFAULT '',
    sha256 TEXT NOT NULL DEFAULT '',
    parser_version TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'en',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_source_documents_published ON source_documents(published_at DESC)`,
  `CREATE TABLE IF NOT EXISTS transcript_segments (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    source_document_id TEXT NOT NULL,
    section TEXT NOT NULL,
    ordinal INTEGER NOT NULL,
    speaker TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL,
    anchor TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    FOREIGN KEY (source_document_id) REFERENCES source_documents(id),
    UNIQUE(source_document_id, ordinal)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_transcript_segments_conversation ON transcript_segments(conversation_id, ordinal)`,
  `CREATE TABLE IF NOT EXISTS knowledge_claims (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    source_document_id TEXT NOT NULL,
    segment_id TEXT NOT NULL,
    claim_type TEXT NOT NULL,
    subject TEXT NOT NULL,
    statement TEXT NOT NULL,
    metric_key TEXT NOT NULL DEFAULT '',
    value_text TEXT NOT NULL DEFAULT '',
    numeric_value REAL,
    unit TEXT NOT NULL DEFAULT '',
    period TEXT NOT NULL DEFAULT '',
    evidence_excerpt TEXT NOT NULL,
    evidence_anchor TEXT NOT NULL,
    confidence INTEGER NOT NULL,
    verification_status TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    FOREIGN KEY (source_document_id) REFERENCES source_documents(id),
    FOREIGN KEY (segment_id) REFERENCES transcript_segments(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_knowledge_claims_conversation_type ON knowledge_claims(conversation_id, claim_type)`,
  `CREATE INDEX IF NOT EXISTS idx_knowledge_claims_metric_period ON knowledge_claims(metric_key, period)`,
  `CREATE TABLE IF NOT EXISTS knowledge_entities (
    id TEXT PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    tickers_json TEXT NOT NULL DEFAULT '[]',
    aliases_json TEXT NOT NULL DEFAULT '[]',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_knowledge_entities_name_type ON knowledge_entities(canonical_name, entity_type)`,
  `CREATE TABLE IF NOT EXISTS conversation_entities (
    conversation_id TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    relation_type TEXT NOT NULL DEFAULT 'subject',
    PRIMARY KEY (conversation_id, entity_id, relation_type),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    FOREIGN KEY (entity_id) REFERENCES knowledge_entities(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_conversation_entities_entity ON conversation_entities(entity_id, conversation_id)`,
] as const;
